# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'DartleSDK' do
pod 'AFNetworking'
pod 'PromiseKit'
pod 'PromiseKit-AFNetworking'
pod 'FDKeychain'
end

target 'DartleSDKTests' do

end

